version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    stdin_open: true
    volumes:
      - "./src:/app/src"
    depends_on:
      - db
  
  db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./mongo-entrypoint:/docker-entrypoint-initdb.d
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
